### ISSUE TITLE
Add concept of a PM

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#359]
For NodeBB, this would just alias to Chat; however, Chat is such a provider-specific term, it'd be bizarre to implement private messages under that name in other providers, like IRC and Slack. When plugins want a private message, knowing it's a Chat is weird.

**Comment by yamikuronue** [comment]
It would also be great to alias Topic and Thread.

**Comment by AccaliaDeElementia** [comment]
hmm..... honestly if we do that i'd be for changing the name of Chat to PrivateMessage and adding a transition alias as Chat, with proper deprecation warnings about a scheduled removal.

as for Topic vs Thread i'm less convinced. Topic seems to be a more agnostic term than thread, especially as i can see sockbot providers for a hierarchical post system where there aren't threads, but rather topic trees.

in either case i'd be rather against a permanent aliasing of concepts, but a rename and a transition alias i can get behind.

**Comment by yamikuronue** [comment]
How do you figure? You can have a "thread of conversation" just as well as you can have a "topic of conversation" ,but "thread" is more widely used in the forum space. 

I feel like the actual implementations should use the most widely used term, and if the specific provider wants to alias their provider-specific name for a concept, they can.

**Comment by AccaliaDeElementia** [comment]
I'l be honest, thread vs. topic is mostly a gut feeling and personal preference.

i personally prefer topic because that's how i categorize my communication, i have topics of communication, rather than threads of communication.

that being said i feel it's vastly more important to be interoperable with different providers in sockbot so if the name thread is more meaningful to those developers who will be writing and maintaining plugins and providers then the name should be changed, i'm just not really sold on changing the name. I can see it working either way to be honest.
