### ISSUE TITLE
Release number buggy

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockBot#380]
Since the move to semantic release, we can no longer tell the release number from the package json if installed using github:

`|zoidberg | [2016-10-21T13:19:27.708Z] Starting Sockbot 0.0.0-semantic-release - undefined`

**Comment by AccaliaDeElementia** [comment]
hmm..... the inability to get the release number from package.json is actually by design when using semantic release as that package manages setting the version on publish.

that being said there should be some process for at least getting the commit that is running when running a development version.

I'll look into it.
